# Retrieve the first 50 products of the category "vodkas"

GET https://world.openfoodfacts.org/category/vodkas.json?page_size=50
Accept: application/json

###

# Retrieve the first 50 products of the ingredient collection "cognac"

GET https://world.openfoodfacts.org/ingredient/cognac.json?page_size=50
Accept: application/json
